import { CollectionItem } from '../model'
import { RoutePath } from './routes'
import {
  DIGIMONS_BACKUP,
  DIGIMONS_SHINY_BACKUP,
  DRAGON_BALL_BLACK_DOT_BACKUP,
  DRAGON_BALL_FLEER_1_BACKUP,
  DRAGON_BALL_FLEER_2_BACKUP,
  DRAGON_BALL_FLEER_3_BACKUP,
  DRAGON_BALL_NO_CIRCLES_BACKUP,
  DRAGON_BALL_Z_RED_DOT_BACKUP,
  DRAGON_BALL_Z_YELLOW_DOT_BACKUP,
  JACKIE_CHAN_BACKUP,
  JACKIE_CHAN_STAR_BACKUP,
  LION_KING_BACKUP
} from './backups'

export const INIT_APP_CONFIG: Array<{ path: RoutePath, coll: CollectionItem[] }> = [
  { path: RoutePath.DRAGON_BALL_Z_YELLOW_DOT, coll: DRAGON_BALL_Z_YELLOW_DOT_BACKUP },
  { path: RoutePath.DRAGON_BALL_Z_RED_DOT, coll: DRAGON_BALL_Z_RED_DOT_BACKUP },
  { path: RoutePath.DRAGON_BALL_BLACK_DOT, coll: DRAGON_BALL_BLACK_DOT_BACKUP },
  { path: RoutePath.DRAGON_BALL_NO_CIRCLE, coll: DRAGON_BALL_NO_CIRCLES_BACKUP },
  { path: RoutePath.DRAGON_BALL_FLEER_1, coll: DRAGON_BALL_FLEER_1_BACKUP },
  { path: RoutePath.DRAGON_BALL_FLEER_2, coll: DRAGON_BALL_FLEER_2_BACKUP },
  { path: RoutePath.DRAGON_BALL_FLEER_3, coll: DRAGON_BALL_FLEER_3_BACKUP },
  { path: RoutePath.LION_KING, coll: LION_KING_BACKUP },
  { path: RoutePath.DIGIMONS, coll: DIGIMONS_BACKUP },
  { path: RoutePath.DIGIMONS_SHINY, coll: DIGIMONS_SHINY_BACKUP },
  { path: RoutePath.JACKIE_CHAN, coll: JACKIE_CHAN_BACKUP },
  { path: RoutePath.JACKIE_CHAN_STAR, coll: JACKIE_CHAN_STAR_BACKUP }
]
